export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "id" }];
}

import Footer from "@/components/common/footer/footer";
import NavigationBar from "@/components/common/navigation/navigation-bar";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: "en" | "id" };
}>) {
  return (
    <html lang={params.lang}>
      <body className={`${plusJakartaSans.variable} antialiased`}>
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
