export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "id" }];
}

import Footer from "@/components/common/footer/footer";
import NavigationBar from "@/components/common/navigation/navigation-bar";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Lang } from "@/types/lang";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<Lang>;
}>) {
  const lang = (await params).lang;
  return (
    <html lang={lang}>
      <body className={`${plusJakartaSans.variable} antialiased`}>
        <NavigationBar params={params} />
        {children}
        <Footer params={params}/>
      </body>
    </html>
  );
}
